#!/usr/bin/env bash
# PulseNode — one-command installer
# Usage: curl -fsSL https://raw.githubusercontent.com/SakithaSamarathunga33/vps/main/install.sh | bash
set -euo pipefail

G='\033[0;32m'; C='\033[0;36m'; Y='\033[1;33m'; R='\033[0;31m'; B='\033[1m'; N='\033[0m'

REPO_URL="https://github.com/SakithaSamarathunga33/vps.git"
INSTALL_DIR="${PULSENODE_DIR:-$HOME/pulsenode}"
[[ "$(id -u)" == "0" ]] && INSTALL_DIR="/opt/pulsenode"

echo -e "${C}${B}"
cat << 'BANNER'
  ____        _          _   _           _
 |  _ \ _   _| |___  ___| \ | | ___   __| | ___
 | |_) | | | | / __|/ _ \  \| |/ _ \ / _` |/ _ \
 |  __/| |_| | \__ \  __/ |\  | (_) | (_| |  __/
 |_|    \__,_|_|___/\___|_| \_|\___/ \__,_|\___|
BANNER
echo -e "${N}${G}  One-command VPS monitoring dashboard installer${N}"
echo ""

# ── Prerequisites ──────────────────────────────────────────────────────────────
check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    echo -e "${R}✗ $1 is not installed.${N}  $2"
    exit 1
  fi
}
check_cmd git    "Install: sudo apt-get install git"
check_cmd curl   "Install: sudo apt-get install curl"
check_cmd docker "Install Docker: https://docs.docker.com/get-docker/"
if ! docker compose version &>/dev/null 2>&1; then
  echo -e "${R}✗ Docker Compose v2 not available.${N}"
  echo "  Update Docker or install the Compose plugin:"
  echo "  https://docs.docker.com/compose/install/"
  exit 1
fi

echo -e "${G}✓ git            $(git --version | awk '{print $3}')${N}"
echo -e "${G}✓ Docker         $(docker --version | awk '{print $3}' | tr -d ',')${N}"
echo -e "${G}✓ Docker Compose $(docker compose version --short 2>/dev/null || echo 'v2')${N}"
echo ""

# ── Clone or update ────────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR/.git" ]]; then
  echo -e "${C}━━━  Updating existing install at ${INSTALL_DIR}  ━━━━━━━━━━━━━━━${N}"
  git -C "$INSTALL_DIR" pull --ff-only
else
  echo -e "${C}━━━  Cloning PulseNode into ${INSTALL_DIR}  ━━━━━━━━━━━━━━━━━━━━${N}"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"
echo ""

# ── Detect public IP ───────────────────────────────────────────────────────────
DETECTED_IP=$(
  curl -fsSL --max-time 5 https://api.ipify.org 2>/dev/null ||
  curl -fsSL --max-time 5 https://ifconfig.me   2>/dev/null ||
  hostname -I 2>/dev/null | awk '{print $1}'    ||
  echo "localhost"
)

echo -e "${C}━━━  Access URL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
printf "  Detected IP: ${B}%s${N}\n" "$DETECTED_IP"
printf "  Install at http://%s/ ? [Y/n]: " "$DETECTED_IP"
read -r CONFIRM </dev/tty || CONFIRM="y"
if [[ "${CONFIRM,,}" == "n" ]]; then
  printf "  Enter your VPS IP or hostname: "
  read -r DETECTED_IP </dev/tty
fi
HOST="${DETECTED_IP#https://}"; HOST="${HOST#http://}"; HOST="${HOST%%/*}"
BASE_URL="http://${HOST}"
WS_URL="ws://${HOST}"
echo ""

# ── Write .env.local ───────────────────────────────────────────────────────────
API_SECRET=$(openssl rand -hex 32 2>/dev/null \
  || head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 32)

echo -e "${C}━━━  Writing configuration  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
cat > .env.local << EOF
# PulseNode — generated by install.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
NEXT_PUBLIC_ORIGIN=${BASE_URL}
NEXT_PUBLIC_NODE_API=${BASE_URL}
NEXT_PUBLIC_PYTHON_API=${BASE_URL}
NEXT_PUBLIC_WS_URL=${WS_URL}
WEB_PORT=127.0.0.1:3000
NODE_PORT=127.0.0.1:4001
PYTHON_PORT=127.0.0.1:8001
LISTEN_PORT=80
NODE_API_AUTH=false
NODE_API_SECRET=${API_SECRET}
COOLIFY_API_URL=
COOLIFY_API_TOKEN=
DATABASE_URL=
EOF
echo -e "  ${G}✓ .env.local written${N}"
echo ""

# ── Pull pre-built images or build from source ─────────────────────────────────
echo -e "${C}━━━  Starting containers  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"

COMPOSE_BASE="-f docker-compose.yml -f docker-compose.standalone.yml"

if docker compose $COMPOSE_BASE -f docker-compose.ghcr.yml pull 2>/dev/null; then
  echo -e "  ${G}✓ Using pre-built images from GitHub Container Registry${N}"
  echo ""
  docker compose $COMPOSE_BASE -f docker-compose.ghcr.yml up -d
else
  echo -e "  ${Y}Pre-built images unavailable — building from source (this takes a few minutes)...${N}"
  echo ""
  docker compose $COMPOSE_BASE up -d --build
fi

# ── Wait for services ──────────────────────────────────────────────────────────
echo ""
echo -e "${C}━━━  Waiting for services to be ready  ━━━━━━━━━━━━━━━━━━━━━${N}"
WAIT=0
until curl -fsSL --max-time 2 "http://localhost/health" &>/dev/null; do
  if (( WAIT >= 60 )); then
    echo -e "\n  ${Y}⚠ Taking longer than expected. Check: docker compose logs${N}"
    break
  fi
  printf "\r  Waiting... %ds" "$WAIT"
  sleep 3
  WAIT=$((WAIT + 3))
done
printf "\r  ${G}✓ Services ready${N}          \n"
echo ""

# ── Done ───────────────────────────────────────────────────────────────────────
echo -e "${G}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
echo -e "${G}${B}  ✓  PulseNode is live!${N}"
echo ""
echo -e "  ${B}Open in browser  →  ${C}${BASE_URL}/${N}"
echo ""
echo -e "  ${B}Quick links:${N}"
echo -e "    ${C}${BASE_URL}/containers${N}"
echo -e "    ${C}${BASE_URL}/stats${N}"
echo -e "    ${C}${BASE_URL}/processes${N}"
echo -e "    ${C}${BASE_URL}/databases${N}"
echo ""
echo -e "  Installed at:  ${Y}${INSTALL_DIR}${N}"
echo -e "  To stop:       ${Y}docker compose -f docker-compose.yml -f docker-compose.standalone.yml down${N}"
echo -e "  To update:     ${Y}curl -fsSL https://raw.githubusercontent.com/SakithaSamarathunga33/vps/main/install.sh | bash${N}"
echo -e "${G}${B}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${N}"
